/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import base.Grafo;
import base.Main;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import outros.ReaderDoc;

/**
 *
 * @author Jorge
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    private JFileChooser JFCFiles;
    private Grafo grafo;
    
    public Home() {
        JFCFiles = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("TxT file", new String[]{"txt"});   //Mostrar e escolher somentes txts
        JFCFiles.setDialogTitle("Selecionar Arquivo");
        JFCFiles.setFileFilter(filter);
        JFCFiles.addChoosableFileFilter(filter);
        JFCFiles.setAcceptAllFileFilterUsed(false);
        initComponents();
    }
    
    public Home(Grafo grafo) {
        this.grafo = grafo;
        JFCFiles = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("TxT file", new String[]{"txt"});   //Mostrar e escolher somentes txts
        JFCFiles.setDialogTitle("Selecionar Arquivo");
        JFCFiles.setFileFilter(filter);
        JFCFiles.addChoosableFileFilter(filter);
        JFCFiles.setAcceptAllFileFilterUsed(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        bttSelecionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bttIr1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bttIr2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bttIr3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel1.setText("Bem Vindo");

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel2.setText("Arquivo:");

        jtfEndereco.setEditable(false);
        jtfEndereco.setBackground(new java.awt.Color(255, 255, 255));
        jtfEndereco.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        bttSelecionar.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        bttSelecionar.setText("Selecionar");
        bttSelecionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSelecionarActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outros/zika-zerojpg145588045456c6f906e95ad.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttIr1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        bttIr1.setText("Ir");
        bttIr1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttIr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttIr1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel4.setText("1º Problema");

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel5.setText("2º Problema");

        bttIr2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        bttIr2.setText("Ir");
        bttIr2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttIr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttIr2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel6.setText("3º Problema");

        bttIr3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        bttIr3.setText("Ir");
        bttIr3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttIr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttIr3ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("O Maranhão registrou em janeiro\ndeste ano 105 casos de microcefalia\nassociados ao Zica vírus.\nAtentos a esta problemática o \ngovernador resolveu adotar algumas \nmedidas.\n1. Nas cidades que apresentaram \ncasos de dengue, zika ou \nchikungunya haverá um carro fumacê\nrodando diariamente pela cidade \npara fazer os trabalhos de \ndedetização.\n2. Na capital haverá um centro de \nacompanhamento e tratamento \nexclusivo para portadores de\nmicrocefalia (CATeMI).");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(bttIr1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(219, 219, 219)
                                        .addComponent(jLabel5)
                                        .addGap(193, 193, 193))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bttIr2)
                                        .addGap(205, 205, 205)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bttIr3)
                                        .addGap(10, 10, 10))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttSelecionar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttSelecionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttIr1)
                    .addComponent(bttIr2)
                    .addComponent(bttIr3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSelecionarActionPerformed
        if(JFCFiles.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            jtfEndereco.setText(JFCFiles.getSelectedFile().getAbsolutePath());
            try {
                grafo = ReaderDoc.getWords(jtfEndereco.getText());
                System.out.println("Carregado");
            } catch (FileNotFoundException ex) {
                System.out.println("Erro");
            }
        }
    }//GEN-LAST:event_bttSelecionarActionPerformed

    private void bttIr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttIr1ActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new Problema1(this.grafo));
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttIr1ActionPerformed

    private void bttIr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttIr2ActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new Problema2(this.grafo));
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttIr2ActionPerformed

    private void bttIr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttIr3ActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new Problema3(this.grafo));
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttIr3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttIr1;
    private javax.swing.JButton bttIr2;
    private javax.swing.JButton bttIr3;
    private javax.swing.JButton bttSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jtfEndereco;
    // End of variables declaration//GEN-END:variables
}
